// flow-typed signature: dcb6b674f7cec39edfa9a18dd80ebf2c
// flow-typed version: <<STUB>>/gulp-watch_v~5.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-watch/index' {
  declare module.exports: $Exports<'gulp-watch'>;
}
declare module 'gulp-watch/index.js' {
  declare module.exports: $Exports<'gulp-watch'>;
}
