// flow-typed signature: 2eb588c8f39ecf86350796dd1e8b778c
// flow-typed version: <<STUB>>/gulp-cli_v~2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-cli/bin/gulp' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/ansi' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/cli-options' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/completion' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/config/cli-flags' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/config/env-flags' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/config/load-files' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/exit' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/get-blacklist' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/blacklist-error' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/copy-tree' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/tasks' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/to-console' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/verify' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/make-title' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/register-exports' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/tildify' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/verify-dependencies' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/format-error' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/log/events' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/log/tasks-simple' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/task-tree' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.1/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.2/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/format-error' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/events' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/get-task' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/sync-task' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/tasks-simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-cli/bin/gulp.js' {
  declare module.exports: $Exports<'gulp-cli/bin/gulp'>;
}
declare module 'gulp-cli/index' {
  declare module.exports: $Exports<'gulp-cli'>;
}
declare module 'gulp-cli/index.js' {
  declare module.exports: $Exports<'gulp-cli'>;
}
declare module 'gulp-cli/lib/shared/ansi.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/ansi'>;
}
declare module 'gulp-cli/lib/shared/cli-options.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/cli-options'>;
}
declare module 'gulp-cli/lib/shared/completion.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/completion'>;
}
declare module 'gulp-cli/lib/shared/config/cli-flags.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/config/cli-flags'>;
}
declare module 'gulp-cli/lib/shared/config/env-flags.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/config/env-flags'>;
}
declare module 'gulp-cli/lib/shared/config/load-files.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/config/load-files'>;
}
declare module 'gulp-cli/lib/shared/exit.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/exit'>;
}
declare module 'gulp-cli/lib/shared/get-blacklist.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/get-blacklist'>;
}
declare module 'gulp-cli/lib/shared/log/blacklist-error.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/blacklist-error'>;
}
declare module 'gulp-cli/lib/shared/log/copy-tree.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/copy-tree'>;
}
declare module 'gulp-cli/lib/shared/log/tasks.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/tasks'>;
}
declare module 'gulp-cli/lib/shared/log/to-console.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/to-console'>;
}
declare module 'gulp-cli/lib/shared/log/verify.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/verify'>;
}
declare module 'gulp-cli/lib/shared/make-title.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/make-title'>;
}
declare module 'gulp-cli/lib/shared/register-exports.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/register-exports'>;
}
declare module 'gulp-cli/lib/shared/tildify.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/tildify'>;
}
declare module 'gulp-cli/lib/shared/verify-dependencies.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/verify-dependencies'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/format-error.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/format-error'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/index'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/log/events.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/log/events'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/log/tasks-simple.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/log/tasks-simple'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/task-tree.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/task-tree'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0-alpha.1/index'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0-alpha.2/index'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/format-error.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/format-error'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/index'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/events.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/events'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/get-task.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/get-task'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/sync-task.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/sync-task'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/tasks-simple.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/tasks-simple'>;
}
